version: '3.5'

services:
  botanday:
    image: botanday
    build: .
    container_name: botanday
    restart: always
    networks:
      - postgres
    env_file:
      - ./.env

networks:
  postgres:  
    external: true